version: 2

# Explicitly set os and the version of Python
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
